monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - clionly

when@dev:
    monolog:
        handlers:
            web:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event", "!clionly"]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console", "!clionly"]
            command:
                type: stream
                path: "%kernel.logs_dir%/console.log"
                channels: [clionly]

when@test:
    monolog:
        handlers:
            web:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!clionly"]
            command:
                type: noop
                channels: [clionly]

when@prod:
    monolog:
        handlers:
            web:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: notice
                max_files: 7
                channels: ["!clionly"]
            web_error_filter:
                type: fingers_crossed
                action_level: error
                handler: web_error_mail
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
                channels: ["!clionly"]
            web_error_mail:
                type: native_mailer
                from_email: '%env(resolve:ALERTS_EMAIL)%'
                to_email: '%env(resolve:ALERTS_EMAIL)%'
                subject: '[MATI] Prod web errors'
                level: debug
                channels: ["!clionly"]
            command:
                type: rotating_file
                path: "%kernel.logs_dir%/console.log"
                level: info
                max_files: 7
                channels: [clionly]
            command_error_filter:
                type: fingers_crossed
                action_level: error
                handler: command_error_mail
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
                channels: [clionly]
            command_error_mail:
                type: native_mailer
                from_email: '%env(resolve:ALERTS_EMAIL)%'
                to_email: '%env(resolve:ALERTS_EMAIL)%'
                subject: '[MATI] Prod cli errors'
                level: debug
                channels: [clionly]
            deprecation:
                type: error_log
                channels: [deprecation]
