name: CI
on:
  push:
    branches:
      - master
      - staging
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/ci.yml'
      - 'README.md'
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/icantsneed/mati-superchats:master
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: composer install
      - name: Run lint
        run: composer lint
  deploy_prod:
    name: Deploy to prod
    if: ${{ github.ref_name == 'master' }}
    uses: ./.github/workflows/deploy.yml
    with:
      environmentName: 'prod'
      environmentUrl: 'https://mati.x10.mx'
    secrets: inherit
  deploy_staging:
    name: Deploy to staging
    if: ${{ github.ref_name == 'staging' }}
    uses: ./.github/workflows/deploy.yml
    with:
      environmentName: 'staging'
      environmentUrl: 'https://staging.mati.x10.mx'
    secrets: inherit
