name: Build and Deploy
on:
  workflow_dispatch:
    inputs:
      containerTag:
        description: 'Container tag'
        required: true
        default: 'master'
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/icantsneed/mati-superchats:${{ inputs.containerTag }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        APP_ENV: prod
        APP_DEBUG: 0
        DATABASE_URL: bogus
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader
      - name: Run pre-deploy command
        run: php bin/predeploy
      - name: Zip up required files
        run: zip -r -9 mati.zip bin/ config/ html/ migrations/ src/ .env composer.json -x html/deploy.php
      - name: Deploy archive
        run: |
          curl -v -k --fail-with-body --stderr - -H "X-Mati-Deploy: ${{ secrets.DEPLOYKEY }}" -F "archive=@mati.zip" https://mati.x10.mx/deploy.php
