name: Build and Deploy
on:
  workflow_dispatch:
    inputs:
      containerTag:
        description: 'Container tag'
        required: true
        default: 'master'
      environmentName:
        description: 'Deployment environment'
        required: true
        default: 'prod'
      environmentUrl:
        description: 'Deployment environment URL'
        required: true
        default: 'https://mati.x10.mx'
  workflow_call:
    inputs:
      containerTag:
        type: string
        default: 'master'
      environmentName:
        type: string
        required: true
      environmentUrl:
        type: string
        required: true
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/icantsneed/mati-superchats:${{ inputs.containerTag }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    environment:
      name: ${{ inputs.environmentName }}
      url: ${{ inputs.environmentUrl }}
    steps:
      - uses: actions/checkout@v4
      - name: Create revision file
        run: echo "$GITHUB_RUN_NUMBER.$GITHUB_RUN_ATTEMPT" > .revision
      - name: Download external assets
        run: bash ./bin/assets
      - name: Deploy
        env:
          FTP_REMOTE: ${{ secrets.FTP_REMOTE }}
          DEPLOYKEY: ${{ secrets.DEPLOYKEY }}
          ROOT_URL: ${{ inputs.environmentUrl }}
        run: php /root/composer-dev/vendor/bin/deployment deployment.php
