name: Build and Deploy
on:
  workflow_dispatch:
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/icantsneed/mati-superchats:master
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: php /root/.composer/vendor/bin/deployment deployment.php
