name: Build and Deploy
on:
  workflow_dispatch:
    inputs:
      containerTag:
        description: 'Container tag'
        required: true
        default: 'master'
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/icantsneed/mati-superchats:${{ inputs.containerTag }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Create revision file
        run: echo "$GITHUB_RUN_NUMBER.$GITHUB_RUN_ATTEMPT" > .revision
      - name: Download external assets
        run: bash ./bin/assets
      - name: Deploy
        env:
          FTP_REMOTE: ${{ secrets.FTP_REMOTE }}
          DEPLOYKEY: ${{ secrets.DEPLOYKEY }}
        run: php /root/.composer/vendor/bin/deployment deployment.php
