name: CI
on:
  workflow_call:
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/icantsneed/mati-superchats:master
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: composer install
      - name: Run lint
        run: composer lint
